/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gr.open.loglevelsmanager.loglevel.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LogLevel service. Represents a row in the &quot;loglevel_LogLevel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link gr.open.loglevelsmanager.loglevel.model.impl.LogLevelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link gr.open.loglevelsmanager.loglevel.model.impl.LogLevelImpl}.
 * </p>
 *
 * @author Jack A. Rider
 * @see LogLevel
 * @see gr.open.loglevelsmanager.loglevel.model.impl.LogLevelImpl
 * @see gr.open.loglevelsmanager.loglevel.model.impl.LogLevelModelImpl
 * @generated
 */
public interface LogLevelModel extends BaseModel<LogLevel>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a log level model instance should use the {@link LogLevel} interface instead.
	 */

	/**
	 * Returns the primary key of this log level.
	 *
	 * @return the primary key of this log level
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this log level.
	 *
	 * @param primaryKey the primary key of this log level
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the log level ID of this log level.
	 *
	 * @return the log level ID of this log level
	 */
	public long getLogLevelId();

	/**
	 * Sets the log level ID of this log level.
	 *
	 * @param LogLevelId the log level ID of this log level
	 */
	public void setLogLevelId(long LogLevelId);

	/**
	 * Returns the company ID of this log level.
	 *
	 * @return the company ID of this log level
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this log level.
	 *
	 * @param companyId the company ID of this log level
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this log level.
	 *
	 * @return the group ID of this log level
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this log level.
	 *
	 * @param groupId the group ID of this log level
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this log level.
	 *
	 * @return the user ID of this log level
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this log level.
	 *
	 * @param userId the user ID of this log level
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this log level.
	 *
	 * @return the user uuid of this log level
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this log level.
	 *
	 * @param userUuid the user uuid of this log level
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this log level.
	 *
	 * @return the user name of this log level
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this log level.
	 *
	 * @param userName the user name of this log level
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this log level.
	 *
	 * @return the create date of this log level
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this log level.
	 *
	 * @param createDate the create date of this log level
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this log level.
	 *
	 * @return the modified date of this log level
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this log level.
	 *
	 * @param modifiedDate the modified date of this log level
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the log level description of this log level.
	 *
	 * @return the log level description of this log level
	 */
	@AutoEscape
	public String getLogLevelDescription();

	/**
	 * Sets the log level description of this log level.
	 *
	 * @param logLevelDescription the log level description of this log level
	 */
	public void setLogLevelDescription(String logLevelDescription);

	/**
	 * Returns the log level priority of this log level.
	 *
	 * @return the log level priority of this log level
	 */
	@AutoEscape
	public String getLogLevelPriority();

	/**
	 * Sets the log level priority of this log level.
	 *
	 * @param logLevelPriority the log level priority of this log level
	 */
	public void setLogLevelPriority(String logLevelPriority);

	/**
	 * Returns the log level category of this log level.
	 *
	 * @return the log level category of this log level
	 */
	@AutoEscape
	public String getLogLevelCategory();

	/**
	 * Sets the log level category of this log level.
	 *
	 * @param logLevelCategory the log level category of this log level
	 */
	public void setLogLevelCategory(String logLevelCategory);

	/**
	 * Returns the log level scheduled of this log level.
	 *
	 * @return the log level scheduled of this log level
	 */
	public boolean getLogLevelScheduled();

	/**
	 * Returns <code>true</code> if this log level is log level scheduled.
	 *
	 * @return <code>true</code> if this log level is log level scheduled; <code>false</code> otherwise
	 */
	public boolean isLogLevelScheduled();

	/**
	 * Sets whether this log level is log level scheduled.
	 *
	 * @param logLevelScheduled the log level scheduled of this log level
	 */
	public void setLogLevelScheduled(boolean logLevelScheduled);

	/**
	 * Returns the log level start date of this log level.
	 *
	 * @return the log level start date of this log level
	 */
	public Date getLogLevelStartDate();

	/**
	 * Sets the log level start date of this log level.
	 *
	 * @param logLevelStartDate the log level start date of this log level
	 */
	public void setLogLevelStartDate(Date logLevelStartDate);

	/**
	 * Returns the log level end date of this log level.
	 *
	 * @return the log level end date of this log level
	 */
	public Date getLogLevelEndDate();

	/**
	 * Sets the log level end date of this log level.
	 *
	 * @param logLevelEndDate the log level end date of this log level
	 */
	public void setLogLevelEndDate(Date logLevelEndDate);

	/**
	 * Returns the activate on startup of this log level.
	 *
	 * @return the activate on startup of this log level
	 */
	public boolean getActivateOnStartup();

	/**
	 * Returns <code>true</code> if this log level is activate on startup.
	 *
	 * @return <code>true</code> if this log level is activate on startup; <code>false</code> otherwise
	 */
	public boolean isActivateOnStartup();

	/**
	 * Sets whether this log level is activate on startup.
	 *
	 * @param activateOnStartup the activate on startup of this log level
	 */
	public void setActivateOnStartup(boolean activateOnStartup);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LogLevel logLevel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LogLevel> toCacheModel();

	@Override
	public LogLevel toEscapedModel();

	@Override
	public LogLevel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}